theme: jekyll-theme-cayman
title: Alpheios Embedded Library Simple Mode Demo Site
description: A demonstration using Alpheios embed-lib on a Github pages site.
include: [node_modules]
keep_files: [node_modules]
